Repository 78-artilleryman/Studit, pull requests merged in 2024-04, with the labels that each got.

#39 Feat: post-detail page
  src/App.tsx
  src/pages/detail/PostDetail.style.ts
  src/pages/detail/PostDetail.tsx
  src/pages/detail/components/Contents.tsx
  src/pages/detail/components/HashTag.style.ts
  src/pages/detail/components/HashTag.tsx
  src/pages/detail/components/PostHeader.style.ts
  src/pages/detail/components/PostHeader.tsx
  src/pages/detail/components/StudyInfo.style.ts
  src/pages/detail/components/StudyInfo.tsx
  src/pages/home/Home.tsx
  src/pages/index.ts
  src/styles/colors.ts
Labels: UI

#41 feat: main page 무한 스크롤 구현
  src/pages/home/Home.tsx
  src/pages/home/components/postItem/PostItem.tsx
  src/pages/home/components/postLIst/PostList.tsx
  src/pages/home/hooks/.gitkeep
  src/pages/home/hooks/usePagination.ts
  src/pages/home/service/Filter.ts
  src/pages/home/service/FormatDate.ts
  src/pages/home/service/Search.ts
Labels: Refactoring, Feature

#46 Feat: PageNotFound
  src/App.tsx
  src/pages/index.ts
  src/pages/notfound/NotFound.style.ts
  src/pages/notfound/NotFound.tsx
Labels: UI

#49 main 페이지 추가 작업
  package-lock.json
  package.json
  src/hooks/useSelect.ts
  src/pages/home/Home.tsx
  src/pages/home/components/commonFilter/CommonFilter.tsx
  src/pages/home/components/postItem/PostItem.tsx
  src/pages/home/components/postLIst/PostList.tsx
  src/pages/home/components/searchBar/SearchBar.tsx
  src/pages/home/components/skeleton/Skeleton.style.tsx
  src/pages/home/components/skeleton/Skeleton.tsx
  src/pages/home/components/technologyFilter/TechnologyFilter.tsx
  src/pages/home/components/undefinedButton/UndefinedButton.style.tsx
  src/pages/home/components/undefinedButton/UndefinedButton.tsx
  src/pages/home/hooks/usePagination.ts
  src/pages/home/service/FormatDate.ts
  src/pages/post/components/commonSelectBox/CommonSelectBox.tsx
  src/pages/post/components/technologySelectBox/TechnologySelectBox.tsx
  src/styles/colors.ts
Labels: Feature, UI

#50 Feat: Social Login 앱 추가
  src/pages/auth/service/social.ts
Labels: Bug

#51 이메일 중복검사 및 비밀번호기 보기/가리기 버튼
  public/images/auth/eye-off-icon.svg
  public/images/auth/eye-on-icon.svg
  src/components/form-compound/Form.tsx
  src/components/form-compound/FormControl.style.ts
  src/components/form-compound/FormControl.tsx
  src/hooks/useToggle.ts
  src/pages/auth/Login.tsx
  src/pages/auth/Register.tsx
  src/pages/auth/components/form-control/FormControlEmail.tsx
  src/pages/auth/components/form-control/FormControlName.tsx
  src/pages/auth/components/form-control/FormControlPassword.tsx
  src/pages/auth/components/form-control/FormControlPasswordConfirm.tsx
  src/pages/auth/components/form-control/index.tsx
  src/pages/auth/hooks/useInput.ts
  src/pages/auth/hooks/usePasswordConfirm.ts
  src/pages/auth/service/auth.ts
  src/pages/auth/service/social.ts
  src/pages/auth/utils/firebase-auth.ts
  src/pages/auth/utils/validate/index.ts
  src/pages/auth/utils/validate/validate-email.ts
  src/pages/auth/utils/validate/validate-name.ts
  src/pages/auth/utils/validate/validate-password.ts
  src/pages/auth/utils/validate/validate-utils.ts
  src/pages/auth/utils/validation.ts
Labels: Refactoring, Feature, UI

#52 Post 페이지 추가 개발
  src/pages/post/Post.tsx
  src/pages/post/components/actionButtons/ActionButtons.tsx
  src/pages/post/components/postForm/PostForm.style.tsx
  src/pages/post/components/postForm/PostForm.tsx
  src/pages/post/components/selectBoxList/data.ts
  src/pages/post/components/textEditor/TextEditor.style.tsx
  src/pages/post/components/textEditor/TextEditor.tsx
  src/pages/post/context/PostDataContext.tsx
  src/pages/post/util/EmptyString.ts
Labels: Feature, UI
