Repository 78-artilleryman/Studit, pull requests merged in 2024-03, with the labels that each got.

#7 Project setup
  craco.config.js
  package-lock.json
  package.json
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/App.css
  src/App.test.tsx
  src/App.tsx
  src/index.tsx
  src/logo.svg
  src/pages/home/Home.tsx
  src/pages/home/components/.gitkeep
  src/pages/home/context/.gitkeep
  src/pages/home/hooks/.gitkeep
  src/pages/home/service/.gitkeep
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/setupTests.ts
  tsconfig.json
  tsconfig.paths.json
Labels: Init

#12 Register
  package-lock.json
  package.json
  src/App.tsx
  src/components/Input/Input.style.ts
  src/components/Input/Input.tsx
  src/components/UI/Button.style.ts
  src/components/UI/Button.tsx
  src/layouts/InputLayout.style.ts
  src/pages/Root.tsx
  src/pages/index.ts
  src/pages/register/Register.style.ts
  src/pages/register/Register.tsx
  src/styles/colors.ts
  src/styles/myReset.ts
  tsconfig.paths.json
Labels: UI

#11 메인 페이지에 필요한 UI 생성
  .prettierrc
  package-lock.json
  package.json
  public/logoImages/filterStack/F-comcss.png
  public/logoImages/filterStack/F-css.png
  public/logoImages/filterStack/F-javascript.png
  public/logoImages/filterStack/F-nextjs.png
  public/logoImages/filterStack/F-postcss.png
  public/logoImages/filterStack/F-react.png
  public/logoImages/filterStack/F-sass.png
  public/logoImages/filterStack/F-styledcomponent.png
  public/logoImages/filterStack/F-tailwind.png
  public/logoImages/filterStack/F-typescript.png
  public/postLogoImages/CSS.svg
  public/postLogoImages/JavaScript.svg
  public/postLogoImages/NextJs.svg
  public/postLogoImages/PostCss.svg
  public/postLogoImages/ReactJs.svg
  public/postLogoImages/Scss.svg
  public/postLogoImages/StyledComponents.svg
  public/postLogoImages/Tailwind.svg
  public/postLogoImages/TypeScript.svg
  src/App.tsx
  src/pages/main/Main.tsx
  src/pages/main/components/CommonFilter/CommonFilter.style.tsx
  src/pages/main/components/CommonFilter/CommonFilter.tsx
  src/pages/main/components/FilterList/FilterList.tsx
  src/pages/main/components/FilterList/data.ts
  src/pages/main/components/postItem/PostItem.style.tsx
  src/pages/main/components/postItem/PostItem.tsx
  src/pages/main/components/postLIst/PostList.tsx
  src/pages/main/components/postLIst/mockdata.ts
  src/pages/main/components/searchBar/SearchBar.style.tsx
  src/pages/main/components/searchBar/SearchBar.tsx
  src/pages/main/components/technologyFilter/TechnologyFilter.style.tsx
  src/pages/main/components/technologyFilter/TechnologyFilter.tsx
  src/pages/main/components/technologyFilter/TechnologyItem.style.tsx
  src/pages/main/components/technologyFilter/TechnologyItem.tsx
  src/pages/main/hooks/useSelect.ts
Labels: UI

#15 design: post card ui 디자인 추가 및 변경
  package-lock.json
  src/pages/home/Home.tsx
  src/pages/home/components/.gitkeep
  src/pages/home/components/commonFilter/CommonFilter.style.tsx
  src/pages/home/components/commonFilter/CommonFilter.tsx
  src/pages/home/components/filterList/FilterList.tsx
  src/pages/home/components/filterList/data.ts
  src/pages/home/components/postItem/PostItem.style.tsx
  src/pages/home/components/postItem/PostItem.tsx
  src/pages/home/components/postLIst/PostList.tsx
  src/pages/home/components/postLIst/mockdata.ts
  src/pages/home/components/searchBar/SearchBar.style.tsx
  src/pages/home/components/searchBar/SearchBar.tsx
  src/pages/home/components/technologyFilter/TechnologyFilter.style.tsx
  src/pages/home/components/technologyFilter/TechnologyFilter.tsx
  src/pages/home/components/technologyFilter/TechnologyItem.style.tsx
  src/pages/home/components/technologyFilter/TechnologyItem.tsx
  src/pages/home/hooks/.gitkeep
  src/pages/home/hooks/useSelect.ts
  src/pages/main/Main.tsx
  src/pages/main/components/postItem/PostItem.tsx
  src/pages/main/components/postLIst/PostList.tsx
Labels: UI

#18 Feat: Header Components
  src/components/header/Header.style.ts
  src/components/header/Header.tsx
  src/pages/Root.tsx
  src/styles/myReset.ts
  src/styles/rule.ts
Labels: UI

#20 Feat: Login UI
  public/images/auth/github-login.svg
  public/images/auth/google-login.svg
  src/App.tsx
  src/pages/auth/Auth.style.ts
  src/pages/auth/Login.tsx
  src/pages/auth/Register.tsx
  src/pages/index.ts
  src/pages/register/Register.style.ts
  src/pages/register/Register.tsx
Labels: Refactoring, UI

#23 Login feature
  src/components/Input/Input.style.ts
  src/components/Input/Input.tsx
  src/components/UI/Button.style.ts
  src/components/UI/Button.tsx
  src/pages/auth/Auth.style.ts
  src/pages/auth/Login.tsx
  src/pages/auth/Register.tsx
  src/pages/auth/hooks/useInput.ts
  src/pages/auth/hooks/usePasswordConfirm.ts
  src/pages/auth/utils/validation.ts
  src/styles/colors.ts
Labels: Refactoring, Feature, UI

#26 post page UI 구현
  package-lock.json
  package.json
  src/pages/home/components/commonFilter/CommonFilter.tsx
  src/pages/home/components/technologyFilter/TechnologyFilter.tsx
  src/pages/post/Post.tsx
  src/pages/post/components/actionButtons/ActionButtons.tsx
  src/pages/post/components/commonSelectBox/CommonSelectBox.style.tsx
  src/pages/post/components/commonSelectBox/CommonSelectBox.tsx
  src/pages/post/components/formLabel/FormLabel.tsx
  src/pages/post/components/postForm/PostForm.style.tsx
  src/pages/post/components/postForm/PostForm.tsx
  src/pages/post/components/selectBoxList/SelectBoxList.tsx
  src/pages/post/components/technologySelectBox/TechnologyBoxItem.style.tsx
  src/pages/post/components/technologySelectBox/TechnologySelectBox.style.tsx
  src/pages/post/components/technologySelectBox/TechnologySelectBox.tsx
  src/pages/post/components/textEditor/TextEditor.style.tsx
  src/pages/post/components/textEditor/TextEditor.tsx
Labels: Refactoring, UI

#27 feat: post page Feature
  package-lock.json
  package.json
  src/App.tsx
  src/config/firebaseApp.ts
  src/hooks/useSelect.ts
  src/pages/home/components/commonFilter/CommonFilter.style.tsx
  src/pages/home/components/postItem/PostItem.style.tsx
  src/pages/home/components/searchBar/SearchBar.style.tsx
  src/pages/home/components/technologyFilter/TechnologyFilter.style.tsx
  src/pages/home/components/technologyFilter/TechnologyFilter.tsx
  src/pages/home/components/technologyFilter/TechnologyItem.style.tsx
  src/pages/post/Post.tsx
  src/pages/post/components/actionButtons/ActionButtons.tsx
  src/pages/post/components/commonSelectBox/CommonSelectBox.style.tsx
  src/pages/post/components/commonSelectBox/CommonSelectBox.tsx
  src/pages/post/components/postForm/PostForm.style.tsx
  src/pages/post/components/postForm/PostForm.tsx
  src/pages/post/components/selectBoxList/SelectBoxList.tsx
  src/pages/post/components/selectBoxList/data.ts
  src/pages/post/components/technologySelectBox/TechnologyBoxItem.style.tsx
  src/pages/post/components/technologySelectBox/TechnologyBoxItem.tsx
  src/pages/post/components/technologySelectBox/TechnologySelectBox.style.tsx
  src/pages/post/components/technologySelectBox/TechnologySelectBox.tsx
  src/pages/post/components/textEditor/TextEditor.tsx
  src/pages/post/context/.gitkeep
  src/pages/post/context/PostDataContext.tsx
  src/pages/post/interface/PostType.ts
  src/styles/colors.ts
  tsconfig.paths.json
Labels: Feature

#31 Feat: Compound Pattern 적용
  src/App.tsx
  src/components/Input/Input.tsx
  src/components/form-compound/Form.style.ts
  src/components/form-compound/Form.tsx
  src/components/form-compound/FormControl.style.ts
  src/components/form-compound/FormControl.tsx
  src/pages/auth/Login.tsx
  src/pages/auth/Register.tsx
  src/pages/auth/hooks/useInput.ts
  src/pages/auth/hooks/usePasswordConfirm.ts
  src/pages/auth/utils/firebase-auth.ts
Labels: Refactoring, UI

#34 메인 페이지 기능구현
  src/App.tsx
  src/components/header/Header.tsx
  src/pages/auth/context/AuthContext.tsx
  src/pages/auth/utils/firebase-auth.ts
  src/pages/home/Home.tsx
  src/pages/home/components/commonFilter/CommonFilter.tsx
  src/pages/home/components/filterList/FilterList.tsx
  src/pages/home/components/filterList/data.ts
  src/pages/home/components/postItem/PostItem.tsx
  src/pages/home/components/postLIst/PostList.tsx
  src/pages/home/components/technologyFilter/TechnologyItem.style.tsx
  src/pages/home/components/technologyFilter/TechnologyItem.tsx
  src/pages/home/context/.gitkeep
  src/pages/home/context/FilterContext.tsx
  src/pages/home/service/Filter.ts
  src/pages/post/Post.tsx
  src/pages/post/components/technologySelectBox/TechnologyBoxItem.tsx
Labels: Refactoring, Feature

#35 post item에 들어갈 날짜 계산 후 삽입 & 검색 기능 추가
  src/pages/home/Home.tsx
  src/pages/home/components/postItem/PostItem.style.tsx
  src/pages/home/components/postItem/PostItem.tsx
  src/pages/home/components/postLIst/PostList.tsx
  src/pages/home/components/searchBar/SearchBar.style.tsx
  src/pages/home/components/searchBar/SearchBar.tsx
  src/pages/home/interface/Types.ts
  src/pages/home/service/FormatDate.ts
  src/pages/home/service/Search.ts
Labels: Refactoring, Feature
